name: run main.py

on:
  push:
    branches:
    - main
    # - 'Testing'

# on:
#    schedule:
#         # run at 8am every Monday
#        - cron: "00 15 * * 1"
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          
      - name: execute py script # run main.py
        env:
          GEE_AUTH: ${{secrets.GEE_AUTH}}
          GDRIVE_AUTH: ${{secrets.GDRIVE_AUTH}}
        run: python main.py
        
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated report" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: share report # send gmails with html attachment
        env:
          GMAIL_PWD: ${{secrets.GMAIL_PWD }}
          GEE_AUTH: ${{secrets.GEE_AUTH}}
        run: |
          python share.py  # Replace with your script filename