name: run main.py

on:
  push:
    branches:
      - main
      - 'Testing'

# on:
#     schedule:
#         # run at 2pm every Wendsday
#         - cron: "00 14 * * 3"
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
# decrypt secret    
#       - uses: actions/checkout@v3
#       - name: Decrypt large secret
#         run: gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output $HOME/tnc-birdreturn-test-c95e19825893.json tnc-birdreturn-test-c95e19825893.json.gpg
#         env:
#           GMAIL_PWD: ${{ secrets.GMAIL_PWD }}
#           GEE_AUTH: ${{secrets.GEE_AUTH}}
#       - name: execute py script # run main.py
#         run: python main.py 
          
      - name: execute py script # run main.py
        uses: datapane/build-action@v2
        env:
          GMAIL_PWD: ${{ secrets.GMAIL_PWD }}
#           LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
#           GEE_AUTH: ${{secrets.GEE_AUTH}}
        with:
          script: "main.py"
          token: ${{ secrets.DATAPANE_TOKEN }}

          
#       - name: commit files
#         run: |
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git add -A
#           git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
#       - name: push changes
#         uses: ad-m/github-push-action@v0.6.0
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: main 
